import type { Metadata } from "next";
import StoreProvider from "./StoreProvider";
import { AuthProvider } from "./components/AuthProvider";
import "./styles/globals.css";
import "./styles/custom-progress-bar.css";
export const metadata: Metadata = {
  title: "Summarist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <AuthProvider>
              
            {children}
              
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
