import type { Metadata } from "next";
import "./styles/globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import Modal from "./components/Modal";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>

          {children}
          
        </StoreProvider>
      </body>
    </html>
  );
}
